import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsCloud: SidebarsConfig = {
  cloudSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsCloud;
